[package]
name = "7kayoh/fusionrouter"
description = "UI Routing for Fusion"
license = "MIT"
author = "7kayoh <hello@7kayoh.net>"
version = "0.1.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
